# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_3_0.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 768)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 230, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 133, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 230, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 133, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 230, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_sim = QtWidgets.QPushButton(self.centralwidget)
        self.start_sim.setGeometry(QtCore.QRect(500, 30, 121, 41))
        self.start_sim.setStyleSheet("")
        self.start_sim.setCheckable(True)
        self.start_sim.setObjectName("start_sim")
        self.stop_sim = QtWidgets.QPushButton(self.centralwidget)
        self.stop_sim.setGeometry(QtCore.QRect(500, 210, 121, 41))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.stop_sim.setFont(font)
        self.stop_sim.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.stop_sim.setCheckable(False)
        self.stop_sim.setChecked(False)
        self.stop_sim.setAutoDefault(False)
        self.stop_sim.setDefault(False)
        self.stop_sim.setFlat(False)
        self.stop_sim.setObjectName("stop_sim")
        self.pause_sim = QtWidgets.QPushButton(self.centralwidget)
        self.pause_sim.setGeometry(QtCore.QRect(500, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pause_sim.setFont(font)
        self.pause_sim.setStyleSheet("QPushButton{\n"
"\n"
"}\n"
"\n"
".glow-on-hover {\n"
"    width: 220px;\n"
"    height: 50px;\n"
"    border: none;\n"
"    outline: none;\n"
"    color: #fff;\n"
"    background: #111;\n"
"    cursor: pointer;\n"
"    position: relative;\n"
"    z-index: 0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
".glow-on-hover:before {\n"
"    content: \'\';\n"
"    background: linear-gradient(45deg, #ff0000, #ff7300, #fffb00, #48ff00, #00ffd5, #002bff, #7a00ff, #ff00c8, #ff0000);\n"
"    position: absolute;\n"
"    top: -2px;\n"
"    left:-2px;\n"
"    background-size: 400%;\n"
"    z-index: -1;\n"
"    filter: blur(5px);\n"
"    width: calc(100% + 4px);\n"
"    height: calc(100% + 4px);\n"
"    animation: glowing 20s linear infinite;\n"
"    opacity: 0;\n"
"    transition: opacity .3s ease-in-out;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
".glow-on-hover:active {\n"
"    color: #000\n"
"}\n"
"\n"
".glow-on-hover:active:after {\n"
"    background: transparent;\n"
"}\n"
"\n"
".glow-on-hover:hover:before {\n"
"    opacity: 1;\n"
"}\n"
"\n"
".glow-on-hover:after {\n"
"    z-index: -1;\n"
"    content: \'\';\n"
"    position: absolute;\n"
"    width: 100%;\n"
"    height: 100%;\n"
"    background: #111;\n"
"    left: 0;\n"
"    top: 0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"@keyframes glowing {\n"
"    0% { background-position: 0 0; }\n"
"    50% { background-position: 400% 0; }\n"
"    100% { background-position: 0 0; }\n"
"}\n"
"")
        self.pause_sim.setObjectName("pause_sim")
        self.sim_param_frame = QtWidgets.QFrame(self.centralwidget)
        self.sim_param_frame.setEnabled(True)
        self.sim_param_frame.setGeometry(QtCore.QRect(20, 20, 441, 211))
        self.sim_param_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sim_param_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sim_param_frame.setObjectName("sim_param_frame")
        self.title = QtWidgets.QLabel(self.sim_param_frame)
        self.title.setGeometry(QtCore.QRect(190, 20, 71, 20))
        self.title.setObjectName("title")
        self.history = QtWidgets.QCheckBox(self.sim_param_frame)
        self.history.setGeometry(QtCore.QRect(20, 80, 101, 20))
        self.history.setObjectName("history")
        self.pots = QtWidgets.QCheckBox(self.sim_param_frame)
        self.pots.setGeometry(QtCore.QRect(20, 110, 91, 20))
        self.pots.setObjectName("pots")
        self.line_5 = QtWidgets.QFrame(self.sim_param_frame)
        self.line_5.setGeometry(QtCore.QRect(20, 50, 401, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_4 = QtWidgets.QLabel(self.sim_param_frame)
        self.label_4.setGeometry(QtCore.QRect(244, 80, 121, 41))
        self.label_4.setObjectName("label_4")
        self.Apply_sim_param = QtWidgets.QPushButton(self.sim_param_frame)
        self.Apply_sim_param.setGeometry(QtCore.QRect(230, 160, 93, 28))
        self.Apply_sim_param.setObjectName("Apply_sim_param")
        self.Reset_sim_params = QtWidgets.QPushButton(self.sim_param_frame)
        self.Reset_sim_params.setGeometry(QtCore.QRect(330, 160, 93, 28))
        self.Reset_sim_params.setObjectName("Reset_sim_params")
        self.sim_info = QtWidgets.QGroupBox(self.centralwidget)
        self.sim_info.setGeometry(QtCore.QRect(640, 20, 161, 651))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sim_info.setFont(font)
        self.sim_info.setStyleSheet("groupBox_3{\n"
"font: Times new roman;\n"
"font-size:14px;\n"
"}")
        self.sim_info.setFlat(False)
        self.sim_info.setObjectName("sim_info")
        self.sim_time_show = QtWidgets.QLCDNumber(self.sim_info)
        self.sim_time_show.setGeometry(QtCore.QRect(78, 26, 64, 23))
        self.sim_time_show.setSmallDecimalPoint(True)
        self.sim_time_show.setObjectName("sim_time_show")
        self.text = QtWidgets.QLabel(self.sim_info)
        self.text.setGeometry(QtCore.QRect(10, 32, 55, 16))
        self.text.setObjectName("text")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.sim_info)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 60, 101, 571))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_18 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_18.sizePolicy().hasHeightForWidth())
        self.line_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_18.setFont(font)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_2.addWidget(self.line_18, 11, 0, 1, 2)
        self.x_t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_t.sizePolicy().hasHeightForWidth())
        self.x_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.x_t.setFont(font)
        self.x_t.setAutoFillBackground(False)
        self.x_t.setStyleSheet("")
        self.x_t.setObjectName("x_t")
        self.gridLayout_2.addWidget(self.x_t, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.w_g = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_g.sizePolicy().hasHeightForWidth())
        self.w_g.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.w_g.setFont(font)
        self.w_g.setObjectName("w_g")
        self.gridLayout_2.addWidget(self.w_g, 18, 0, 1, 1)
        self.w_b = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_b.sizePolicy().hasHeightForWidth())
        self.w_b.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.w_b.setFont(font)
        self.w_b.setObjectName("w_b")
        self.gridLayout_2.addWidget(self.w_b, 16, 0, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_20.sizePolicy().hasHeightForWidth())
        self.line_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_20.setFont(font)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_2.addWidget(self.line_20, 15, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 5, 0, 1, 2)
        self.alpha = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alpha.sizePolicy().hasHeightForWidth())
        self.alpha.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.alpha.setFont(font)
        self.alpha.setObjectName("alpha")
        self.gridLayout_2.addWidget(self.alpha, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line.setWindowModality(QtCore.Qt.ApplicationModal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.line_17 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_17.sizePolicy().hasHeightForWidth())
        self.line_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_17.setFont(font)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_2.addWidget(self.line_17, 9, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 7, 0, 1, 2)
        self.gama = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gama.sizePolicy().hasHeightForWidth())
        self.gama.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.gama.setFont(font)
        self.gama.setObjectName("gama")
        self.gridLayout_2.addWidget(self.gama, 12, 0, 1, 1)
        self.beta = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beta.sizePolicy().hasHeightForWidth())
        self.beta.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.beta.setFont(font)
        self.beta.setObjectName("beta")
        self.gridLayout_2.addWidget(self.beta, 10, 0, 1, 1)
        self.z_t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_t.sizePolicy().hasHeightForWidth())
        self.z_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.z_t.setFont(font)
        self.z_t.setStyleSheet("label_13{\n"
"text-align: center;\n"
"}")
        self.z_t.setObjectName("z_t")
        self.gridLayout_2.addWidget(self.z_t, 4, 0, 1, 1)
        self.v_t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_t.sizePolicy().hasHeightForWidth())
        self.v_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.v_t.setFont(font)
        self.v_t.setObjectName("v_t")
        self.gridLayout_2.addWidget(self.v_t, 6, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_19.sizePolicy().hasHeightForWidth())
        self.line_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_19.setFont(font)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_2.addWidget(self.line_19, 13, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 2)
        self.y_t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_t.sizePolicy().hasHeightForWidth())
        self.y_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.y_t.setFont(font)
        self.y_t.setObjectName("y_t")
        self.gridLayout_2.addWidget(self.y_t, 2, 0, 1, 1)
        self.w_a = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_a.sizePolicy().hasHeightForWidth())
        self.w_a.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.w_a.setFont(font)
        self.w_a.setObjectName("w_a")
        self.gridLayout_2.addWidget(self.w_a, 14, 0, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_21.sizePolicy().hasHeightForWidth())
        self.line_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_21.setFont(font)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_2.addWidget(self.line_21, 17, 0, 1, 2)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 0, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 2, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 4, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 6, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_2.addWidget(self.label_54, 8, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_2.addWidget(self.label_55, 10, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_2.addWidget(self.label_56, 12, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 14, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_2.addWidget(self.label_58, 16, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_2.addWidget(self.label_59, 18, 1, 1, 1)
        self.Reset_sim = QtWidgets.QPushButton(self.centralwidget)
        self.Reset_sim.setGeometry(QtCore.QRect(502, 87, 121, 41))
        self.Reset_sim.setObjectName("Reset_sim")
        self.connectioninfo = QtWidgets.QGroupBox(self.centralwidget)
        self.connectioninfo.setGeometry(QtCore.QRect(20, 689, 781, 41))
        self.connectioninfo.setFlat(True)
        self.connectioninfo.setCheckable(False)
        self.connectioninfo.setObjectName("connectioninfo")
        self.connection_text = QtWidgets.QLabel(self.connectioninfo)
        self.connection_text.setGeometry(QtCore.QRect(14, 19, 751, 21))
        self.connection_text.setObjectName("connection_text")
        self.pid_set_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.pid_set_widget.setGeometry(QtCore.QRect(20, 250, 571, 411))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 202, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.pid_set_widget.setPalette(palette)
        self.pid_set_widget.setDocumentMode(False)
        self.pid_set_widget.setTabsClosable(False)
        self.pid_set_widget.setTabBarAutoHide(False)
        self.pid_set_widget.setObjectName("pid_set_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(30, 130, 301, 191))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 281, 174))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.slider_yaw_1 = QtWidgets.QSlider(self.layoutWidget_4)
        self.slider_yaw_1.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_yaw_1.setMinimum(-45)
        self.slider_yaw_1.setMaximum(45)
        self.slider_yaw_1.setSingleStep(0)
        self.slider_yaw_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_yaw_1.setObjectName("slider_yaw_1")
        self.verticalLayout_6.addWidget(self.slider_yaw_1)
        self.line_38 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.verticalLayout_6.addWidget(self.line_38)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_6.addWidget(self.label_29)
        self.slider_roll_1 = QtWidgets.QSlider(self.layoutWidget_4)
        self.slider_roll_1.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_roll_1.setMinimum(-45)
        self.slider_roll_1.setMaximum(45)
        self.slider_roll_1.setSingleStep(0)
        self.slider_roll_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_roll_1.setObjectName("slider_roll_1")
        self.verticalLayout_6.addWidget(self.slider_roll_1)
        self.line_39 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.verticalLayout_6.addWidget(self.line_39)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.slider_pitch_1 = QtWidgets.QSlider(self.layoutWidget_4)
        self.slider_pitch_1.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_pitch_1.setMinimum(-45)
        self.slider_pitch_1.setMaximum(45)
        self.slider_pitch_1.setSingleStep(1)
        self.slider_pitch_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_pitch_1.setObjectName("slider_pitch_1")
        self.verticalLayout_6.addWidget(self.slider_pitch_1)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(350, 130, 171, 191))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 151, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.SpinBox_kp_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_kp_1.setReadOnly(False)
        self.SpinBox_kp_1.setProperty("showGroupSeparator", False)
        self.SpinBox_kp_1.setMinimum(-20.0)
        self.SpinBox_kp_1.setMaximum(20.0)
        self.SpinBox_kp_1.setSingleStep(0.01)
        self.SpinBox_kp_1.setObjectName("SpinBox_kp_1")
        self.gridLayout.addWidget(self.SpinBox_kp_1, 0, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.SpinBox_ki_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_ki_1.setReadOnly(False)
        self.SpinBox_ki_1.setProperty("showGroupSeparator", False)
        self.SpinBox_ki_1.setMinimum(-20.0)
        self.SpinBox_ki_1.setMaximum(20.0)
        self.SpinBox_ki_1.setSingleStep(0.01)
        self.SpinBox_ki_1.setObjectName("SpinBox_ki_1")
        self.gridLayout.addWidget(self.SpinBox_ki_1, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 3, 0, 1, 2)
        self.SpinBox_kd_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_kd_1.setReadOnly(False)
        self.SpinBox_kd_1.setProperty("showGroupSeparator", False)
        self.SpinBox_kd_1.setMinimum(-20.0)
        self.SpinBox_kd_1.setMaximum(20.0)
        self.SpinBox_kd_1.setSingleStep(0.01)
        self.SpinBox_kd_1.setObjectName("SpinBox_kd_1")
        self.gridLayout.addWidget(self.SpinBox_kd_1, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.SpinBox_speed_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_speed_1.setReadOnly(False)
        self.SpinBox_speed_1.setProperty("showGroupSeparator", False)
        self.SpinBox_speed_1.setMinimum(-20.0)
        self.SpinBox_speed_1.setMaximum(20.0)
        self.SpinBox_speed_1.setSingleStep(0.01)
        self.SpinBox_speed_1.setObjectName("SpinBox_speed_1")
        self.gridLayout.addWidget(self.SpinBox_speed_1, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 5, 0, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(10, 30, 531, 311))
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.pid_set_info = QtWidgets.QLabel(self.frame_4)
        self.pid_set_info.setGeometry(QtCore.QRect(40, 20, 451, 51))
        self.pid_set_info.setObjectName("pid_set_info")
        self.line_13 = QtWidgets.QFrame(self.frame_4)
        self.line_13.setGeometry(QtCore.QRect(20, 20, 3, 61))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.frame_4)
        self.line_14.setGeometry(QtCore.QRect(510, 20, 3, 61))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.Apply_1 = QtWidgets.QPushButton(self.tab)
        self.Apply_1.setGeometry(QtCore.QRect(350, 350, 93, 28))
        self.Apply_1.setObjectName("Apply_1")
        self.Reset_1 = QtWidgets.QPushButton(self.tab)
        self.Reset_1.setGeometry(QtCore.QRect(450, 350, 93, 28))
        self.Reset_1.setObjectName("Reset_1")
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.Apply_1.raise_()
        self.Reset_1.raise_()
        self.pid_set_widget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_11 = QtWidgets.QFrame(self.tab_5)
        self.frame_11.setGeometry(QtCore.QRect(10, 30, 531, 311))
        self.frame_11.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.pid_set_info_5 = QtWidgets.QLabel(self.frame_11)
        self.pid_set_info_5.setGeometry(QtCore.QRect(40, 20, 451, 51))
        self.pid_set_info_5.setObjectName("pid_set_info_5")
        self.line_40 = QtWidgets.QFrame(self.frame_11)
        self.line_40.setGeometry(QtCore.QRect(20, 20, 3, 61))
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.line_41 = QtWidgets.QFrame(self.frame_11)
        self.line_41.setGeometry(QtCore.QRect(510, 20, 3, 61))
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.frame_12 = QtWidgets.QFrame(self.tab_5)
        self.frame_12.setGeometry(QtCore.QRect(30, 130, 301, 191))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame_12)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 10, 281, 174))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_7.addWidget(self.label_31)
        self.slider_yaw_2 = QtWidgets.QSlider(self.layoutWidget_5)
        self.slider_yaw_2.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_yaw_2.setMinimum(-45)
        self.slider_yaw_2.setMaximum(45)
        self.slider_yaw_2.setSingleStep(0)
        self.slider_yaw_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_yaw_2.setObjectName("slider_yaw_2")
        self.verticalLayout_7.addWidget(self.slider_yaw_2)
        self.line_42 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.verticalLayout_7.addWidget(self.line_42)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_7.addWidget(self.label_32)
        self.slider_roll_2 = QtWidgets.QSlider(self.layoutWidget_5)
        self.slider_roll_2.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_roll_2.setMinimum(-45)
        self.slider_roll_2.setMaximum(45)
        self.slider_roll_2.setSingleStep(0)
        self.slider_roll_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_roll_2.setObjectName("slider_roll_2")
        self.verticalLayout_7.addWidget(self.slider_roll_2)
        self.line_43 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.verticalLayout_7.addWidget(self.line_43)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_7.addWidget(self.label_33)
        self.slider_pitch_2 = QtWidgets.QSlider(self.layoutWidget_5)
        self.slider_pitch_2.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_pitch_2.setMinimum(-45)
        self.slider_pitch_2.setMaximum(45)
        self.slider_pitch_2.setSingleStep(1)
        self.slider_pitch_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_pitch_2.setObjectName("slider_pitch_2")
        self.verticalLayout_7.addWidget(self.slider_pitch_2)
        self.frame_13 = QtWidgets.QFrame(self.tab_5)
        self.frame_13.setGeometry(QtCore.QRect(350, 130, 171, 191))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.frame_13)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(9, 9, 151, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line_44 = QtWidgets.QFrame(self.gridLayoutWidget_6)
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.gridLayout_6.addWidget(self.line_44, 1, 0, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 0, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget_6)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_6.addWidget(self.line_9, 3, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 2, 0, 1, 1)
        self.SpinBox_speed_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.SpinBox_speed_2.setReadOnly(False)
        self.SpinBox_speed_2.setProperty("showGroupSeparator", False)
        self.SpinBox_speed_2.setMinimum(-20.0)
        self.SpinBox_speed_2.setMaximum(20.0)
        self.SpinBox_speed_2.setSingleStep(0.01)
        self.SpinBox_speed_2.setObjectName("SpinBox_speed_2")
        self.gridLayout_6.addWidget(self.SpinBox_speed_2, 6, 1, 1, 1)
        self.SpinBox_kp_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.SpinBox_kp_2.setMinimum(-20.0)
        self.SpinBox_kp_2.setMaximum(20.0)
        self.SpinBox_kp_2.setSingleStep(0.01)
        self.SpinBox_kp_2.setObjectName("SpinBox_kp_2")
        self.gridLayout_6.addWidget(self.SpinBox_kp_2, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 6, 0, 1, 1)
        self.SpinBox_ki_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.SpinBox_ki_2.setMinimum(-20.0)
        self.SpinBox_ki_2.setMaximum(20.0)
        self.SpinBox_ki_2.setSingleStep(0.01)
        self.SpinBox_ki_2.setObjectName("SpinBox_ki_2")
        self.gridLayout_6.addWidget(self.SpinBox_ki_2, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 4, 0, 1, 1)
        self.SpinBox_kd_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.SpinBox_kd_2.setMinimum(-20.0)
        self.SpinBox_kd_2.setMaximum(20.0)
        self.SpinBox_kd_2.setSingleStep(0.01)
        self.SpinBox_kd_2.setObjectName("SpinBox_kd_2")
        self.gridLayout_6.addWidget(self.SpinBox_kd_2, 4, 1, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget_6)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_6.addWidget(self.line_10, 5, 0, 1, 2)
        self.Reset_2 = QtWidgets.QPushButton(self.tab_5)
        self.Reset_2.setGeometry(QtCore.QRect(450, 350, 93, 28))
        self.Reset_2.setObjectName("Reset_2")
        self.Apply_2 = QtWidgets.QPushButton(self.tab_5)
        self.Apply_2.setGeometry(QtCore.QRect(350, 350, 93, 28))
        self.Apply_2.setObjectName("Apply_2")
        self.pid_set_widget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.frame_14 = QtWidgets.QFrame(self.tab_6)
        self.frame_14.setGeometry(QtCore.QRect(10, 30, 531, 311))
        self.frame_14.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setObjectName("frame_14")
        self.pid_set_info_6 = QtWidgets.QLabel(self.frame_14)
        self.pid_set_info_6.setGeometry(QtCore.QRect(40, 20, 451, 51))
        self.pid_set_info_6.setObjectName("pid_set_info_6")
        self.line_45 = QtWidgets.QFrame(self.frame_14)
        self.line_45.setGeometry(QtCore.QRect(20, 20, 3, 61))
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.line_46 = QtWidgets.QFrame(self.frame_14)
        self.line_46.setGeometry(QtCore.QRect(510, 20, 3, 61))
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.frame_15 = QtWidgets.QFrame(self.tab_6)
        self.frame_15.setGeometry(QtCore.QRect(30, 130, 301, 191))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_15.setObjectName("frame_15")
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_15)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 10, 281, 174))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_8.addWidget(self.label_36)
        self.slider_yaw_3 = QtWidgets.QSlider(self.layoutWidget_6)
        self.slider_yaw_3.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_yaw_3.setMinimum(-45)
        self.slider_yaw_3.setMaximum(45)
        self.slider_yaw_3.setSingleStep(0)
        self.slider_yaw_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_yaw_3.setObjectName("slider_yaw_3")
        self.verticalLayout_8.addWidget(self.slider_yaw_3)
        self.line_47 = QtWidgets.QFrame(self.layoutWidget_6)
        self.line_47.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.verticalLayout_8.addWidget(self.line_47)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_8.addWidget(self.label_37)
        self.slider_roll_3 = QtWidgets.QSlider(self.layoutWidget_6)
        self.slider_roll_3.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_roll_3.setMinimum(-45)
        self.slider_roll_3.setMaximum(45)
        self.slider_roll_3.setSingleStep(0)
        self.slider_roll_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_roll_3.setObjectName("slider_roll_3")
        self.verticalLayout_8.addWidget(self.slider_roll_3)
        self.line_48 = QtWidgets.QFrame(self.layoutWidget_6)
        self.line_48.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.verticalLayout_8.addWidget(self.line_48)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_8.addWidget(self.label_38)
        self.slider_pitch_3 = QtWidgets.QSlider(self.layoutWidget_6)
        self.slider_pitch_3.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_pitch_3.setMinimum(-45)
        self.slider_pitch_3.setMaximum(45)
        self.slider_pitch_3.setSingleStep(1)
        self.slider_pitch_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_pitch_3.setObjectName("slider_pitch_3")
        self.verticalLayout_8.addWidget(self.slider_pitch_3)
        self.frame_16 = QtWidgets.QFrame(self.tab_6)
        self.frame_16.setGeometry(QtCore.QRect(350, 130, 171, 191))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setObjectName("frame_16")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.frame_16)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(9, 9, 151, 171))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.line_51 = QtWidgets.QFrame(self.gridLayoutWidget_7)
        self.line_51.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.gridLayout_7.addWidget(self.line_51, 1, 0, 1, 2)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 0, 0, 1, 1)
        self.line_49 = QtWidgets.QFrame(self.gridLayoutWidget_7)
        self.line_49.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.gridLayout_7.addWidget(self.line_49, 3, 0, 1, 2)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 2, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 4, 0, 1, 1)
        self.SpinBox_ki_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.SpinBox_ki_3.setMinimum(-20.0)
        self.SpinBox_ki_3.setMaximum(20.0)
        self.SpinBox_ki_3.setSingleStep(0.01)
        self.SpinBox_ki_3.setObjectName("SpinBox_ki_3")
        self.gridLayout_7.addWidget(self.SpinBox_ki_3, 2, 1, 1, 1)
        self.SpinBox_kd_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.SpinBox_kd_3.setMinimum(-20.0)
        self.SpinBox_kd_3.setMaximum(20.0)
        self.SpinBox_kd_3.setSingleStep(0.01)
        self.SpinBox_kd_3.setObjectName("SpinBox_kd_3")
        self.gridLayout_7.addWidget(self.SpinBox_kd_3, 4, 1, 1, 1)
        self.SpinBox_kp_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.SpinBox_kp_3.setMinimum(-20.0)
        self.SpinBox_kp_3.setMaximum(20.0)
        self.SpinBox_kp_3.setSingleStep(0.01)
        self.SpinBox_kp_3.setObjectName("SpinBox_kp_3")
        self.gridLayout_7.addWidget(self.SpinBox_kp_3, 0, 1, 1, 1)
        self.Reset_3 = QtWidgets.QPushButton(self.tab_6)
        self.Reset_3.setGeometry(QtCore.QRect(450, 350, 93, 28))
        self.Reset_3.setObjectName("Reset_3")
        self.Apply_3 = QtWidgets.QPushButton(self.tab_6)
        self.Apply_3.setGeometry(QtCore.QRect(350, 350, 93, 28))
        self.Apply_3.setObjectName("Apply_3")
        self.pid_set_widget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_8 = QtWidgets.QFrame(self.tab_2)
        self.frame_8.setGeometry(QtCore.QRect(10, 30, 531, 311))
        self.frame_8.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.pid_set_info_4 = QtWidgets.QLabel(self.frame_8)
        self.pid_set_info_4.setGeometry(QtCore.QRect(40, 20, 451, 51))
        self.pid_set_info_4.setObjectName("pid_set_info_4")
        self.line_31 = QtWidgets.QFrame(self.frame_8)
        self.line_31.setGeometry(QtCore.QRect(20, 20, 3, 61))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(self.frame_8)
        self.line_32.setGeometry(QtCore.QRect(510, 20, 3, 61))
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(20, 100, 301, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.frame_9.setFont(font)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_9)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 281, 174))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.slider_yaw_4 = QtWidgets.QSlider(self.layoutWidget_3)
        self.slider_yaw_4.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_yaw_4.setMinimum(-45)
        self.slider_yaw_4.setMaximum(45)
        self.slider_yaw_4.setSingleStep(0)
        self.slider_yaw_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_yaw_4.setObjectName("slider_yaw_4")
        self.verticalLayout_5.addWidget(self.slider_yaw_4)
        self.line_33 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.verticalLayout_5.addWidget(self.line_33)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.slider_roll_4 = QtWidgets.QSlider(self.layoutWidget_3)
        self.slider_roll_4.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_roll_4.setMinimum(-45)
        self.slider_roll_4.setMaximum(45)
        self.slider_roll_4.setSingleStep(0)
        self.slider_roll_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_roll_4.setObjectName("slider_roll_4")
        self.verticalLayout_5.addWidget(self.slider_roll_4)
        self.line_34 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.verticalLayout_5.addWidget(self.line_34)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.slider_pitch_4 = QtWidgets.QSlider(self.layoutWidget_3)
        self.slider_pitch_4.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider_pitch_4.setMinimum(-45)
        self.slider_pitch_4.setMaximum(45)
        self.slider_pitch_4.setSingleStep(1)
        self.slider_pitch_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_pitch_4.setObjectName("slider_pitch_4")
        self.verticalLayout_5.addWidget(self.slider_pitch_4)
        self.frame_10 = QtWidgets.QFrame(self.tab_2)
        self.frame_10.setGeometry(QtCore.QRect(350, 130, 171, 191))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_10)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(9, 9, 151, 171))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.SpinBox_ki_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.SpinBox_ki_4.setMinimum(-20.0)
        self.SpinBox_ki_4.setMaximum(20.0)
        self.SpinBox_ki_4.setSingleStep(0.01)
        self.SpinBox_ki_4.setProperty("value", 0.0)
        self.SpinBox_ki_4.setObjectName("SpinBox_ki_4")
        self.gridLayout_5.addWidget(self.SpinBox_ki_4, 2, 1, 1, 1)
        self.SpinBox_kd_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.SpinBox_kd_4.setMinimum(-20.0)
        self.SpinBox_kd_4.setMaximum(20.0)
        self.SpinBox_kd_4.setSingleStep(0.01)
        self.SpinBox_kd_4.setProperty("value", 0.0)
        self.SpinBox_kd_4.setObjectName("SpinBox_kd_4")
        self.gridLayout_5.addWidget(self.SpinBox_kd_4, 4, 1, 1, 1)
        self.SpinBox_kp_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.SpinBox_kp_4.setMinimum(-20.0)
        self.SpinBox_kp_4.setMaximum(20.0)
        self.SpinBox_kp_4.setSingleStep(0.01)
        self.SpinBox_kp_4.setProperty("value", 0.0)
        self.SpinBox_kp_4.setObjectName("SpinBox_kp_4")
        self.gridLayout_5.addWidget(self.SpinBox_kp_4, 0, 1, 1, 1)
        self.line_37 = QtWidgets.QFrame(self.gridLayoutWidget_5)
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.gridLayout_5.addWidget(self.line_37, 1, 0, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 4, 0, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.gridLayoutWidget_5)
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout_5.addWidget(self.line_35, 3, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 2, 0, 1, 1)
        self.Reset_4 = QtWidgets.QPushButton(self.tab_2)
        self.Reset_4.setGeometry(QtCore.QRect(450, 350, 93, 28))
        self.Reset_4.setObjectName("Reset_4")
        self.Apply_4 = QtWidgets.QPushButton(self.tab_2)
        self.Apply_4.setGeometry(QtCore.QRect(350, 350, 93, 28))
        self.Apply_4.setObjectName("Apply_4")
        self.pid_set_widget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuinfo = QtWidgets.QMenu(self.menubar)
        self.menuinfo.setObjectName("menuinfo")
        self.menutrajectory = QtWidgets.QMenu(self.menubar)
        self.menutrajectory.setObjectName("menutrajectory")
        self.menuVisuakisation = QtWidgets.QMenu(self.menubar)
        self.menuVisuakisation.setObjectName("menuVisuakisation")
        MainWindow.setMenuBar(self.menubar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionopen_history = QtWidgets.QAction(MainWindow)
        self.actionopen_history.setObjectName("actionopen_history")
        self.Camera = QtWidgets.QAction(MainWindow)
        self.Camera.setObjectName("Camera")
        self.actionfiltered_camera = QtWidgets.QAction(MainWindow)
        self.actionfiltered_camera.setObjectName("actionfiltered_camera")
        self.actionPath_planer = QtWidgets.QAction(MainWindow)
        self.actionPath_planer.setObjectName("actionPath_planer")
        self.actionview_logs = QtWidgets.QAction(MainWindow)
        self.actionview_logs.setObjectName("actionview_logs")
        self.menufile.addAction(self.actionview_logs)
        self.menuinfo.addAction(self.actionhelp)
        self.menutrajectory.addAction(self.actionPath_planer)
        self.menuVisuakisation.addAction(self.Camera)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuinfo.menuAction())
        self.menubar.addAction(self.menutrajectory.menuAction())
        self.menubar.addAction(self.menuVisuakisation.menuAction())
        self.label_3.setBuddy(self.SpinBox_kd_1)
        self.label.setBuddy(self.SpinBox_kp_1)
        self.label_2.setBuddy(self.SpinBox_ki_1)
        self.label_5.setBuddy(self.SpinBox_kd_1)
        self.label_34.setBuddy(self.SpinBox_kp_1)
        self.label_11.setBuddy(self.SpinBox_ki_1)
        self.label_6.setBuddy(self.SpinBox_kd_1)
        self.label_10.setBuddy(self.SpinBox_kd_1)
        self.label_41.setBuddy(self.SpinBox_kp_1)
        self.label_40.setBuddy(self.SpinBox_ki_1)
        self.label_39.setBuddy(self.SpinBox_kd_1)
        self.label_27.setBuddy(self.SpinBox_kp_1)
        self.label_25.setBuddy(self.SpinBox_kd_1)
        self.label_26.setBuddy(self.SpinBox_ki_1)

        self.retranslateUi(MainWindow)
        self.pid_set_widget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main Controller"))
        self.start_sim.setText(_translate("MainWindow", "Start Simulation"))
        self.stop_sim.setText(_translate("MainWindow", "Stop Simulation"))
        self.pause_sim.setText(_translate("MainWindow", "Pause"))
        self.title.setText(_translate("MainWindow", "Sim Params"))
        self.history.setText(_translate("MainWindow", "Save history"))
        self.pots.setText(_translate("MainWindow", "Ssave plots"))
        self.label_4.setText(_translate("MainWindow", "connected modules"))
        self.Apply_sim_param.setText(_translate("MainWindow", "Apply"))
        self.Reset_sim_params.setText(_translate("MainWindow", "Reset"))
        self.sim_info.setTitle(_translate("MainWindow", "sim info"))
        self.text.setText(_translate("MainWindow", "Sim time"))
        self.x_t.setText(_translate("MainWindow", "X(t) ="))
        self.w_g.setText(_translate("MainWindow", "w(g) ="))
        self.w_b.setText(_translate("MainWindow", "w(b) ="))
        self.alpha.setText(_translate("MainWindow", "alpha ="))
        self.gama.setText(_translate("MainWindow", "gama ="))
        self.beta.setText(_translate("MainWindow", "beta ="))
        self.z_t.setText(_translate("MainWindow", "Z(t) ="))
        self.v_t.setText(_translate("MainWindow", "V(t) ="))
        self.y_t.setText(_translate("MainWindow", "Y(t) ="))
        self.w_a.setText(_translate("MainWindow", "w(a) ="))
        self.label_50.setText(_translate("MainWindow", "0"))
        self.label_51.setText(_translate("MainWindow", "0"))
        self.label_52.setText(_translate("MainWindow", "0"))
        self.label_53.setText(_translate("MainWindow", "0"))
        self.label_54.setText(_translate("MainWindow", "0"))
        self.label_55.setText(_translate("MainWindow", "0"))
        self.label_56.setText(_translate("MainWindow", "0"))
        self.label_57.setText(_translate("MainWindow", "0"))
        self.label_58.setText(_translate("MainWindow", "0"))
        self.label_59.setText(_translate("MainWindow", "0"))
        self.Reset_sim.setText(_translate("MainWindow", "Reset"))
        self.connectioninfo.setTitle(_translate("MainWindow", "Connection"))
        self.connection_text.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "X"))
        self.label_29.setText(_translate("MainWindow", "Y"))
        self.label_30.setText(_translate("MainWindow", "Z"))
        self.label_3.setText(_translate("MainWindow", "Kd"))
        self.label.setText(_translate("MainWindow", "Kp"))
        self.label_2.setText(_translate("MainWindow", "Ki"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.pid_set_info.setText(_translate("MainWindow", "TextLabel"))
        self.Apply_1.setText(_translate("MainWindow", "Apply"))
        self.Reset_1.setText(_translate("MainWindow", "Reset"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.pid_set_info_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_31.setText(_translate("MainWindow", "X"))
        self.label_32.setText(_translate("MainWindow", "Y"))
        self.label_33.setText(_translate("MainWindow", "Z"))
        self.label_34.setText(_translate("MainWindow", "Kp"))
        self.label_11.setText(_translate("MainWindow", "Ki"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Kd"))
        self.Reset_2.setText(_translate("MainWindow", "Reset"))
        self.Apply_2.setText(_translate("MainWindow", "Apply"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.pid_set_info_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_36.setText(_translate("MainWindow", "X"))
        self.label_37.setText(_translate("MainWindow", "Y"))
        self.label_38.setText(_translate("MainWindow", "Z"))
        self.label_41.setText(_translate("MainWindow", "Kp"))
        self.label_40.setText(_translate("MainWindow", "Ki"))
        self.label_39.setText(_translate("MainWindow", "Kd"))
        self.Reset_3.setText(_translate("MainWindow", "Reset"))
        self.Apply_3.setText(_translate("MainWindow", "Apply"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.tab_6), _translate("MainWindow", "Page"))
        self.pid_set_info_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "X"))
        self.label_23.setText(_translate("MainWindow", "Y"))
        self.label_24.setText(_translate("MainWindow", "Z"))
        self.label_27.setText(_translate("MainWindow", "Kp"))
        self.label_25.setText(_translate("MainWindow", "Kd"))
        self.label_26.setText(_translate("MainWindow", "Ki"))
        self.Reset_4.setText(_translate("MainWindow", "Reset"))
        self.Apply_4.setText(_translate("MainWindow", "Apply"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuinfo.setTitle(_translate("MainWindow", "Info"))
        self.menutrajectory.setTitle(_translate("MainWindow", "Trajectory"))
        self.menuVisuakisation.setTitle(_translate("MainWindow", "Visualization"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionopen_history.setText(_translate("MainWindow", "open history"))
        self.Camera.setText(_translate("MainWindow", "Camera"))
        self.actionfiltered_camera.setText(_translate("MainWindow", "filtered camera"))
        self.actionPath_planer.setText(_translate("MainWindow", "Path planer"))
        self.actionview_logs.setText(_translate("MainWindow", "view logs"))
