from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 765)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 230, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 133, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 230, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 133, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 230, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 249, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_sim = QtWidgets.QPushButton(self.centralwidget)
        self.start_sim.setGeometry(QtCore.QRect(500, 30, 121, 41))
        self.start_sim.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.start_sim.setCheckable(True)
        self.start_sim.setObjectName("start_sim")
        self.stop_sim = QtWidgets.QPushButton(self.centralwidget)
        self.stop_sim.setGeometry(QtCore.QRect(500, 210, 121, 41))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.stop_sim.setFont(font)
        self.stop_sim.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.stop_sim.setCheckable(False)
        self.stop_sim.setChecked(False)
        self.stop_sim.setAutoDefault(False)
        self.stop_sim.setDefault(False)
        self.stop_sim.setFlat(False)
        self.stop_sim.setObjectName("stop_sim")
        self.pause_sim = QtWidgets.QPushButton(self.centralwidget)
        self.pause_sim.setGeometry(QtCore.QRect(500, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pause_sim.setFont(font)
        self.pause_sim.setStyleSheet("QPushButton{\n"
"\n"
"}\n"
"\n"
".glow-on-hover {\n"
"    width: 220px;\n"
"    height: 50px;\n"
"    border: none;\n"
"    outline: none;\n"
"    color: #fff;\n"
"    background: #111;\n"
"    cursor: pointer;\n"
"    position: relative;\n"
"    z-index: 0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
".glow-on-hover:before {\n"
"    content: \'\';\n"
"    background: linear-gradient(45deg, #ff0000, #ff7300, #fffb00, #48ff00, #00ffd5, #002bff, #7a00ff, #ff00c8, #ff0000);\n"
"    position: absolute;\n"
"    top: -2px;\n"
"    left:-2px;\n"
"    background-size: 400%;\n"
"    z-index: -1;\n"
"    filter: blur(5px);\n"
"    width: calc(100% + 4px);\n"
"    height: calc(100% + 4px);\n"
"    animation: glowing 20s linear infinite;\n"
"    opacity: 0;\n"
"    transition: opacity .3s ease-in-out;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
".glow-on-hover:active {\n"
"    color: #000\n"
"}\n"
"\n"
".glow-on-hover:active:after {\n"
"    background: transparent;\n"
"}\n"
"\n"
".glow-on-hover:hover:before {\n"
"    opacity: 1;\n"
"}\n"
"\n"
".glow-on-hover:after {\n"
"    z-index: -1;\n"
"    content: \'\';\n"
"    position: absolute;\n"
"    width: 100%;\n"
"    height: 100%;\n"
"    background: #111;\n"
"    left: 0;\n"
"    top: 0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"@keyframes glowing {\n"
"    0% { background-position: 0 0; }\n"
"    50% { background-position: 400% 0; }\n"
"    100% { background-position: 0 0; }\n"
"}\n"
"")
        self.pause_sim.setObjectName("pause_sim")
        self.sim_param_frame = QtWidgets.QFrame(self.centralwidget)
        self.sim_param_frame.setEnabled(True)
        self.sim_param_frame.setGeometry(QtCore.QRect(20, 20, 441, 211))
        self.sim_param_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sim_param_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sim_param_frame.setObjectName("sim_param_frame")
        self.title = QtWidgets.QLabel(self.sim_param_frame)
        self.title.setGeometry(QtCore.QRect(190, 20, 71, 20))
        self.title.setObjectName("title")
        self.history = QtWidgets.QCheckBox(self.sim_param_frame)
        self.history.setGeometry(QtCore.QRect(20, 80, 101, 20))
        self.history.setObjectName("history")
        self.pots = QtWidgets.QCheckBox(self.sim_param_frame)
        self.pots.setGeometry(QtCore.QRect(20, 110, 91, 20))
        self.pots.setObjectName("pots")
        self.line_5 = QtWidgets.QFrame(self.sim_param_frame)
        self.line_5.setGeometry(QtCore.QRect(20, 50, 401, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_4 = QtWidgets.QLabel(self.sim_param_frame)
        self.label_4.setGeometry(QtCore.QRect(244, 80, 121, 41))
        self.label_4.setObjectName("label_4")
        self.Apply_sim_param = QtWidgets.QPushButton(self.sim_param_frame)
        self.Apply_sim_param.setGeometry(QtCore.QRect(230, 160, 93, 28))
        self.Apply_sim_param.setObjectName("Apply_sim_param")
        self.Reset_sim_params = QtWidgets.QPushButton(self.sim_param_frame)
        self.Reset_sim_params.setGeometry(QtCore.QRect(330, 160, 93, 28))
        self.Reset_sim_params.setObjectName("Reset_sim_params")
        self.sim_info = QtWidgets.QGroupBox(self.centralwidget)
        self.sim_info.setGeometry(QtCore.QRect(640, 20, 161, 651))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sim_info.setFont(font)
        self.sim_info.setStyleSheet("groupBox_3{\n"
"font: Times new roman;\n"
"font-size:14px;\n"
"}")
        self.sim_info.setFlat(False)
        self.sim_info.setObjectName("sim_info")
        self.sim_time_show = QtWidgets.QLCDNumber(self.sim_info)
        self.sim_time_show.setGeometry(QtCore.QRect(78, 26, 64, 23))
        self.sim_time_show.setSmallDecimalPoint(True)
        self.sim_time_show.setObjectName("sim_time_show")
        self.text = QtWidgets.QLabel(self.sim_info)
        self.text.setGeometry(QtCore.QRect(10, 32, 55, 16))
        self.text.setObjectName("text")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.sim_info)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 60, 101, 571))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_18 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_18.sizePolicy().hasHeightForWidth())
        self.line_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_18.setFont(font)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_2.addWidget(self.line_18, 11, 0, 1, 2)
        self.x_t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_t.sizePolicy().hasHeightForWidth())
        self.x_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.x_t.setFont(font)
        self.x_t.setAutoFillBackground(False)
        self.x_t.setStyleSheet("")
        self.x_t.setObjectName("x_t")
        self.gridLayout_2.addWidget(self.x_t, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.w_g = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_g.sizePolicy().hasHeightForWidth())
        self.w_g.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.w_g.setFont(font)
        self.w_g.setObjectName("w_g")
        self.gridLayout_2.addWidget(self.w_g, 18, 0, 1, 1)
        self.w_b = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_b.sizePolicy().hasHeightForWidth())
        self.w_b.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.w_b.setFont(font)
        self.w_b.setObjectName("w_b")
        self.gridLayout_2.addWidget(self.w_b, 16, 0, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_20.sizePolicy().hasHeightForWidth())
        self.line_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_20.setFont(font)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_2.addWidget(self.line_20, 15, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 5, 0, 1, 2)
        self.alpha = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alpha.sizePolicy().hasHeightForWidth())
        self.alpha.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.alpha.setFont(font)
        self.alpha.setObjectName("alpha")
        self.gridLayout_2.addWidget(self.alpha, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line.setWindowModality(QtCore.Qt.ApplicationModal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.line_17 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_17.sizePolicy().hasHeightForWidth())
        self.line_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_17.setFont(font)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_2.addWidget(self.line_17, 9, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 7, 0, 1, 2)
        self.gama = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gama.sizePolicy().hasHeightForWidth())
        self.gama.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.gama.setFont(font)
        self.gama.setObjectName("gama")
        self.gridLayout_2.addWidget(self.gama, 12, 0, 1, 1)
        self.beta = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beta.sizePolicy().hasHeightForWidth())
        self.beta.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.beta.setFont(font)
        self.beta.setObjectName("beta")
        self.gridLayout_2.addWidget(self.beta, 10, 0, 1, 1)
        self.z_t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_t.sizePolicy().hasHeightForWidth())
        self.z_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.z_t.setFont(font)
        self.z_t.setStyleSheet("label_13{\n"
"text-align: center;\n"
"}")
        self.z_t.setObjectName("z_t")
        self.gridLayout_2.addWidget(self.z_t, 4, 0, 1, 1)
        self.v_t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_t.sizePolicy().hasHeightForWidth())
        self.v_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.v_t.setFont(font)
        self.v_t.setObjectName("v_t")
        self.gridLayout_2.addWidget(self.v_t, 6, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_19.sizePolicy().hasHeightForWidth())
        self.line_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_19.setFont(font)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_2.addWidget(self.line_19, 13, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 2)
        self.y_t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_t.sizePolicy().hasHeightForWidth())
        self.y_t.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.y_t.setFont(font)
        self.y_t.setObjectName("y_t")
        self.gridLayout_2.addWidget(self.y_t, 2, 0, 1, 1)
        self.w_a = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_a.sizePolicy().hasHeightForWidth())
        self.w_a.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.w_a.setFont(font)
        self.w_a.setObjectName("w_a")
        self.gridLayout_2.addWidget(self.w_a, 14, 0, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_21.sizePolicy().hasHeightForWidth())
        self.line_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.line_21.setFont(font)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_2.addWidget(self.line_21, 17, 0, 1, 2)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 0, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 2, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 4, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 6, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_2.addWidget(self.label_54, 8, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_2.addWidget(self.label_55, 10, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_2.addWidget(self.label_56, 12, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 14, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_2.addWidget(self.label_58, 16, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_2.addWidget(self.label_59, 18, 1, 1, 1)
        self.Reset_sim = QtWidgets.QPushButton(self.centralwidget)
        self.Reset_sim.setGeometry(QtCore.QRect(502, 87, 121, 41))
        self.Reset_sim.setObjectName("Reset_sim")
        self.connectioninfo = QtWidgets.QGroupBox(self.centralwidget)
        self.connectioninfo.setGeometry(QtCore.QRect(20, 689, 781, 41))
        self.connectioninfo.setFlat(True)
        self.connectioninfo.setCheckable(False)
        self.connectioninfo.setObjectName("connectioninfo")
        self.connection_text = QtWidgets.QLabel(self.connectioninfo)
        self.connection_text.setGeometry(QtCore.QRect(14, 19, 751, 21))
        self.connection_text.setObjectName("connection_text")
        self.pid_set_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.pid_set_widget.setGeometry(QtCore.QRect(30, 290, 571, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 202, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.pid_set_widget.setPalette(palette)
        self.pid_set_widget.setDocumentMode(False)
        self.pid_set_widget.setTabsClosable(False)
        self.pid_set_widget.setTabBarAutoHide(False)
        self.pid_set_widget.setObjectName("pid_set_widget")
        self.PID1 = QtWidgets.QWidget()
        self.PID1.setObjectName("PID1")
        self.frame_3 = QtWidgets.QFrame(self.PID1)
        self.frame_3.setGeometry(QtCore.QRect(350, 40, 171, 231))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 151, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 3, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.SpinBox_kv_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_kv_1.setReadOnly(False)
        self.SpinBox_kv_1.setProperty("showGroupSeparator", False)
        self.SpinBox_kv_1.setDecimals(5)
        self.SpinBox_kv_1.setMinimum(-400.0)
        self.SpinBox_kv_1.setMaximum(1000.0)
        self.SpinBox_kv_1.setSingleStep(1e-05)
        self.SpinBox_kv_1.setProperty("value", -2.0)
        self.SpinBox_kv_1.setObjectName("SpinBox_kv_1")
        self.gridLayout.addWidget(self.SpinBox_kv_1, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.SpinBox_ki_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_ki_1.setReadOnly(False)
        self.SpinBox_ki_1.setProperty("showGroupSeparator", False)
        self.SpinBox_ki_1.setDecimals(5)
        self.SpinBox_ki_1.setMinimum(-400.0)
        self.SpinBox_ki_1.setMaximum(1000.0)
        self.SpinBox_ki_1.setSingleStep(1e-05)
        self.SpinBox_ki_1.setProperty("value", 0.0)
        self.SpinBox_ki_1.setObjectName("SpinBox_ki_1")
        self.gridLayout.addWidget(self.SpinBox_ki_1, 2, 1, 1, 1)
        self.SpinBox_kd_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_kd_1.setReadOnly(False)
        self.SpinBox_kd_1.setProperty("showGroupSeparator", False)
        self.SpinBox_kd_1.setDecimals(5)
        self.SpinBox_kd_1.setMinimum(-400.0)
        self.SpinBox_kd_1.setMaximum(100000.0)
        self.SpinBox_kd_1.setSingleStep(1e-05)
        self.SpinBox_kd_1.setProperty("value", 0.0)
        self.SpinBox_kd_1.setObjectName("SpinBox_kd_1")
        self.gridLayout.addWidget(self.SpinBox_kd_1, 4, 1, 1, 1)
        self.SpinBox_kp_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_kp_1.setReadOnly(False)
        self.SpinBox_kp_1.setProperty("showGroupSeparator", False)
        self.SpinBox_kp_1.setDecimals(5)
        self.SpinBox_kp_1.setMinimum(-400.0)
        self.SpinBox_kp_1.setMaximum(1000.0)
        self.SpinBox_kp_1.setSingleStep(1e-05)
        self.SpinBox_kp_1.setProperty("value", 2.0)
        self.SpinBox_kp_1.setObjectName("SpinBox_kp_1")
        self.gridLayout.addWidget(self.SpinBox_kp_1, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 0, 1, 2)
        self.line_13 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 5, 0, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.PID1)
        self.frame_4.setGeometry(QtCore.QRect(10, 20, 531, 271))
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.pid_set_info = QtWidgets.QLabel(self.frame_4)
        self.pid_set_info.setGeometry(QtCore.QRect(67, 50, 221, 181))
        self.pid_set_info.setObjectName("pid_set_info")
        self.line_8 = QtWidgets.QFrame(self.frame_4)
        self.line_8.setGeometry(QtCore.QRect(27, 30, 40, 211))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_10 = QtWidgets.QFrame(self.frame_4)
        self.line_10.setGeometry(QtCore.QRect(277, 30, 40, 211))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.Apply_1 = QtWidgets.QPushButton(self.PID1)
        self.Apply_1.setGeometry(QtCore.QRect(350, 300, 93, 28))
        self.Apply_1.setObjectName("Apply_1")
        self.Reset_1 = QtWidgets.QPushButton(self.PID1)
        self.Reset_1.setGeometry(QtCore.QRect(450, 300, 93, 28))
        self.Reset_1.setObjectName("Reset_1")
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.Apply_1.raise_()
        self.Reset_1.raise_()
        self.pid_set_widget.addTab(self.PID1, "")
        self.PID2 = QtWidgets.QWidget()
        self.PID2.setObjectName("PID2")
        self.frame_11 = QtWidgets.QFrame(self.PID2)
        self.frame_11.setGeometry(QtCore.QRect(10, 20, 531, 271))
        self.frame_11.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.pid_set_info_2 = QtWidgets.QLabel(self.frame_11)
        self.pid_set_info_2.setGeometry(QtCore.QRect(67, 50, 211, 181))
        self.pid_set_info_2.setObjectName("pid_set_info_2")
        self.line_12 = QtWidgets.QFrame(self.frame_11)
        self.line_12.setGeometry(QtCore.QRect(287, 30, 20, 211))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_11 = QtWidgets.QFrame(self.frame_11)
        self.line_11.setGeometry(QtCore.QRect(37, 30, 20, 211))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.frame_13 = QtWidgets.QFrame(self.PID2)
        self.frame_13.setGeometry(QtCore.QRect(350, 40, 171, 231))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.frame_13)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 151, 211))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.SpinBox_ki_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.SpinBox_ki_2.setDecimals(5)
        self.SpinBox_ki_2.setMinimum(-400.0)
        self.SpinBox_ki_2.setMaximum(1000.0)
        self.SpinBox_ki_2.setSingleStep(1e-05)
        self.SpinBox_ki_2.setObjectName("SpinBox_ki_2")
        self.gridLayout_6.addWidget(self.SpinBox_ki_2, 2, 1, 1, 1)
        self.line_44 = QtWidgets.QFrame(self.gridLayoutWidget_6)
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.gridLayout_6.addWidget(self.line_44, 1, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 2, 0, 1, 1)
        self.SpinBox_kd_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.SpinBox_kd_2.setDecimals(5)
        self.SpinBox_kd_2.setMinimum(-400.0)
        self.SpinBox_kd_2.setMaximum(100000.0)
        self.SpinBox_kd_2.setSingleStep(1e-05)
        self.SpinBox_kd_2.setProperty("value", 1.0)
        self.SpinBox_kd_2.setObjectName("SpinBox_kd_2")
        self.gridLayout_6.addWidget(self.SpinBox_kd_2, 4, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 0, 0, 1, 1)
        self.SpinBox_kp_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.SpinBox_kp_2.setDecimals(5)
        self.SpinBox_kp_2.setMinimum(-400.0)
        self.SpinBox_kp_2.setMaximum(1000.0)
        self.SpinBox_kp_2.setSingleStep(1e-05)
        self.SpinBox_kp_2.setProperty("value", 0.005)
        self.SpinBox_kp_2.setObjectName("SpinBox_kp_2")
        self.gridLayout_6.addWidget(self.SpinBox_kp_2, 0, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget_6)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_6.addWidget(self.line_9, 3, 0, 1, 2)
        self.Reset_2 = QtWidgets.QPushButton(self.PID2)
        self.Reset_2.setGeometry(QtCore.QRect(450, 300, 93, 28))
        self.Reset_2.setObjectName("Reset_2")
        self.Apply_2 = QtWidgets.QPushButton(self.PID2)
        self.Apply_2.setGeometry(QtCore.QRect(350, 300, 93, 28))
        self.Apply_2.setObjectName("Apply_2")
        self.pid_set_widget.addTab(self.PID2, "")
        self.PID3 = QtWidgets.QWidget()
        self.PID3.setObjectName("PID3")
        self.frame_14 = QtWidgets.QFrame(self.PID3)
        self.frame_14.setGeometry(QtCore.QRect(10, 20, 531, 271))
        self.frame_14.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setObjectName("frame_14")
        self.line_26 = QtWidgets.QFrame(self.frame_14)
        self.line_26.setGeometry(QtCore.QRect(37, 30, 20, 211))
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_25 = QtWidgets.QFrame(self.frame_14)
        self.line_25.setGeometry(QtCore.QRect(287, 30, 20, 211))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.pid_set_info_5 = QtWidgets.QLabel(self.frame_14)
        self.pid_set_info_5.setGeometry(QtCore.QRect(67, 50, 211, 181))
        self.pid_set_info_5.setObjectName("pid_set_info_5")
        self.frame_16 = QtWidgets.QFrame(self.PID3)
        self.frame_16.setGeometry(QtCore.QRect(350, 40, 171, 231))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setObjectName("frame_16")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.frame_16)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 151, 211))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.SpinBox_kd_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.SpinBox_kd_3.setDecimals(5)
        self.SpinBox_kd_3.setMinimum(-400.0)
        self.SpinBox_kd_3.setMaximum(100000.0)
        self.SpinBox_kd_3.setSingleStep(1e-05)
        self.SpinBox_kd_3.setProperty("value", -1.0)
        self.SpinBox_kd_3.setObjectName("SpinBox_kd_3")
        self.gridLayout_7.addWidget(self.SpinBox_kd_3, 4, 1, 1, 1)
        self.line_51 = QtWidgets.QFrame(self.gridLayoutWidget_7)
        self.line_51.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.gridLayout_7.addWidget(self.line_51, 1, 0, 1, 2)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 2, 0, 1, 1)
        self.SpinBox_ki_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.SpinBox_ki_3.setDecimals(5)
        self.SpinBox_ki_3.setMinimum(-400.0)
        self.SpinBox_ki_3.setMaximum(1000.0)
        self.SpinBox_ki_3.setSingleStep(1e-05)
        self.SpinBox_ki_3.setObjectName("SpinBox_ki_3")
        self.gridLayout_7.addWidget(self.SpinBox_ki_3, 2, 1, 1, 1)
        self.SpinBox_kp_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.SpinBox_kp_3.setDecimals(5)
        self.SpinBox_kp_3.setMinimum(-400.0)
        self.SpinBox_kp_3.setMaximum(1000.0)
        self.SpinBox_kp_3.setSingleStep(1e-05)
        self.SpinBox_kp_3.setProperty("value", -0.005)
        self.SpinBox_kp_3.setObjectName("SpinBox_kp_3")
        self.gridLayout_7.addWidget(self.SpinBox_kp_3, 0, 1, 1, 1)
        self.line_49 = QtWidgets.QFrame(self.gridLayoutWidget_7)
        self.line_49.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.gridLayout_7.addWidget(self.line_49, 3, 0, 1, 2)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 4, 0, 1, 1)
        self.Reset_3 = QtWidgets.QPushButton(self.PID3)
        self.Reset_3.setGeometry(QtCore.QRect(450, 300, 93, 28))
        self.Reset_3.setObjectName("Reset_3")
        self.Apply_3 = QtWidgets.QPushButton(self.PID3)
        self.Apply_3.setGeometry(QtCore.QRect(350, 300, 93, 28))
        self.Apply_3.setObjectName("Apply_3")
        self.pid_set_widget.addTab(self.PID3, "")
        self.PID4 = QtWidgets.QWidget()
        self.PID4.setObjectName("PID4")
        self.frame_8 = QtWidgets.QFrame(self.PID4)
        self.frame_8.setGeometry(QtCore.QRect(10, 20, 531, 271))
        self.frame_8.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setGeometry(QtCore.QRect(340, 20, 171, 231))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_10)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 151, 211))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.SpinBox_ki_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.SpinBox_ki_4.setFont(font)
        self.SpinBox_ki_4.setDecimals(5)
        self.SpinBox_ki_4.setMinimum(-400.0)
        self.SpinBox_ki_4.setMaximum(1000.0)
        self.SpinBox_ki_4.setSingleStep(1e-05)
        self.SpinBox_ki_4.setProperty("value", 0.0)
        self.SpinBox_ki_4.setObjectName("SpinBox_ki_4")
        self.gridLayout_5.addWidget(self.SpinBox_ki_4, 2, 1, 1, 1)
        self.SpinBox_kd_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.SpinBox_kd_4.setFont(font)
        self.SpinBox_kd_4.setDecimals(5)
        self.SpinBox_kd_4.setMinimum(-400.0)
        self.SpinBox_kd_4.setMaximum(100000.0)
        self.SpinBox_kd_4.setSingleStep(1e-05)
        self.SpinBox_kd_4.setProperty("value", 2.0)
        self.SpinBox_kd_4.setObjectName("SpinBox_kd_4")
        self.gridLayout_5.addWidget(self.SpinBox_kd_4, 4, 1, 1, 1)
        self.SpinBox_kp_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setKerning(False)
        self.SpinBox_kp_4.setFont(font)
        self.SpinBox_kp_4.setDecimals(5)
        self.SpinBox_kp_4.setMinimum(-400.0)
        self.SpinBox_kp_4.setMaximum(1000.0)
        self.SpinBox_kp_4.setSingleStep(1e-05)
        self.SpinBox_kp_4.setProperty("value", 0.1)
        self.SpinBox_kp_4.setObjectName("SpinBox_kp_4")
        self.gridLayout_5.addWidget(self.SpinBox_kp_4, 0, 1, 1, 1)
        self.line_37 = QtWidgets.QFrame(self.gridLayoutWidget_5)
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.gridLayout_5.addWidget(self.line_37, 1, 0, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 4, 0, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.gridLayoutWidget_5)
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout_5.addWidget(self.line_35, 3, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 2, 0, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.frame_8)
        self.line_28.setGeometry(QtCore.QRect(37, 30, 20, 211))
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.pid_set_info_6 = QtWidgets.QLabel(self.frame_8)
        self.pid_set_info_6.setGeometry(QtCore.QRect(67, 50, 211, 181))
        self.pid_set_info_6.setObjectName("pid_set_info_6")
        self.line_27 = QtWidgets.QFrame(self.frame_8)
        self.line_27.setGeometry(QtCore.QRect(287, 30, 20, 211))
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.Reset_4 = QtWidgets.QPushButton(self.PID4)
        self.Reset_4.setGeometry(QtCore.QRect(450, 300, 93, 28))
        self.Reset_4.setObjectName("Reset_4")
        self.Apply_4 = QtWidgets.QPushButton(self.PID4)
        self.Apply_4.setGeometry(QtCore.QRect(350, 300, 93, 28))
        self.Apply_4.setObjectName("Apply_4")
        self.pid_set_widget.addTab(self.PID4, "")
        self.PID5 = QtWidgets.QWidget()
        self.PID5.setObjectName("PID5")
        self.frame_17 = QtWidgets.QFrame(self.PID5)
        self.frame_17.setGeometry(QtCore.QRect(10, 20, 531, 271))
        self.frame_17.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_17.setObjectName("frame_17")
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setGeometry(QtCore.QRect(340, 20, 171, 231))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_19.setObjectName("frame_19")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.frame_19)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 151, 211))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.SpinBox_ki_5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.SpinBox_ki_5.setFont(font)
        self.SpinBox_ki_5.setDecimals(5)
        self.SpinBox_ki_5.setMinimum(-400.0)
        self.SpinBox_ki_5.setMaximum(1000.0)
        self.SpinBox_ki_5.setSingleStep(1e-05)
        self.SpinBox_ki_5.setProperty("value", 0.0)
        self.SpinBox_ki_5.setObjectName("SpinBox_ki_5")
        self.gridLayout_8.addWidget(self.SpinBox_ki_5, 2, 1, 1, 1)
        self.SpinBox_kd_5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.SpinBox_kd_5.setFont(font)
        self.SpinBox_kd_5.setDecimals(5)
        self.SpinBox_kd_5.setMinimum(-400.0)
        self.SpinBox_kd_5.setMaximum(100000.0)
        self.SpinBox_kd_5.setSingleStep(1e-05)
        self.SpinBox_kd_5.setProperty("value", 2.1)
        self.SpinBox_kd_5.setObjectName("SpinBox_kd_5")
        self.gridLayout_8.addWidget(self.SpinBox_kd_5, 4, 1, 1, 1)
        self.SpinBox_kp_5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.SpinBox_kp_5.setFont(font)
        self.SpinBox_kp_5.setDecimals(5)
        self.SpinBox_kp_5.setMinimum(-400.0)
        self.SpinBox_kp_5.setMaximum(1000.0)
        self.SpinBox_kp_5.setSingleStep(1e-05)
        self.SpinBox_kp_5.setProperty("value", 0.25)
        self.SpinBox_kp_5.setObjectName("SpinBox_kp_5")
        self.gridLayout_8.addWidget(self.SpinBox_kp_5, 0, 1, 1, 1)
        self.line_54 = QtWidgets.QFrame(self.gridLayoutWidget_8)
        self.line_54.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.gridLayout_8.addWidget(self.line_54, 1, 0, 1, 2)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 4, 0, 1, 1)
        self.line_55 = QtWidgets.QFrame(self.gridLayoutWidget_8)
        self.line_55.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.gridLayout_8.addWidget(self.line_55, 3, 0, 1, 2)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 2, 0, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.frame_17)
        self.line_29.setGeometry(QtCore.QRect(37, 30, 20, 211))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.pid_set_info_7 = QtWidgets.QLabel(self.frame_17)
        self.pid_set_info_7.setGeometry(QtCore.QRect(67, 50, 211, 181))
        self.pid_set_info_7.setObjectName("pid_set_info_7")
        self.line_30 = QtWidgets.QFrame(self.frame_17)
        self.line_30.setGeometry(QtCore.QRect(287, 30, 20, 211))
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.Reset_5 = QtWidgets.QPushButton(self.PID5)
        self.Reset_5.setGeometry(QtCore.QRect(450, 300, 93, 28))
        self.Reset_5.setObjectName("Reset_5")
        self.Apply_5 = QtWidgets.QPushButton(self.PID5)
        self.Apply_5.setGeometry(QtCore.QRect(350, 300, 93, 28))
        self.Apply_5.setObjectName("Apply_5")
        self.pid_set_widget.addTab(self.PID5, "")
        self.PID6 = QtWidgets.QWidget()
        self.PID6.setObjectName("PID6")
        self.frame_20 = QtWidgets.QFrame(self.PID6)
        self.frame_20.setGeometry(QtCore.QRect(10, 20, 531, 271))
        self.frame_20.setStyleSheet("QFrame{\n"
"    background-color: rgb(252, 255, 255);\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_20.setObjectName("frame_20")
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setGeometry(QtCore.QRect(340, 20, 171, 231))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_22.setObjectName("frame_22")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.frame_22)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 151, 211))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.SpinBox_ki_6 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.SpinBox_ki_6.setFont(font)
        self.SpinBox_ki_6.setDecimals(5)
        self.SpinBox_ki_6.setMinimum(-400.0)
        self.SpinBox_ki_6.setMaximum(1000.0)
        self.SpinBox_ki_6.setSingleStep(1e-05)
        self.SpinBox_ki_6.setProperty("value", 0.0)
        self.SpinBox_ki_6.setObjectName("SpinBox_ki_6")
        self.gridLayout_9.addWidget(self.SpinBox_ki_6, 2, 1, 1, 1)
        self.SpinBox_kd_6 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.SpinBox_kd_6.setFont(font)
        self.SpinBox_kd_6.setDecimals(5)
        self.SpinBox_kd_6.setMinimum(-400.0)
        self.SpinBox_kd_6.setMaximum(100000.0)
        self.SpinBox_kd_6.setSingleStep(1e-05)
        self.SpinBox_kd_6.setProperty("value", -2.1)
        self.SpinBox_kd_6.setObjectName("SpinBox_kd_6")
        self.gridLayout_9.addWidget(self.SpinBox_kd_6, 4, 1, 1, 1)
        self.SpinBox_kp_6 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.SpinBox_kp_6.setFont(font)
        self.SpinBox_kp_6.setDecimals(5)
        self.SpinBox_kp_6.setMinimum(-400.0)
        self.SpinBox_kp_6.setMaximum(1000.0)
        self.SpinBox_kp_6.setSingleStep(1e-05)
        self.SpinBox_kp_6.setProperty("value", -0.25)
        self.SpinBox_kp_6.setObjectName("SpinBox_kp_6")
        self.gridLayout_9.addWidget(self.SpinBox_kp_6, 0, 1, 1, 1)
        self.line_60 = QtWidgets.QFrame(self.gridLayoutWidget_9)
        self.line_60.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_60.setObjectName("line_60")
        self.gridLayout_9.addWidget(self.line_60, 1, 0, 1, 2)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_9.addWidget(self.label_47, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 4, 0, 1, 1)
        self.line_61 = QtWidgets.QFrame(self.gridLayoutWidget_9)
        self.line_61.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_61.setObjectName("line_61")
        self.gridLayout_9.addWidget(self.line_61, 3, 0, 1, 2)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 2, 0, 1, 1)
        self.line_31 = QtWidgets.QFrame(self.frame_20)
        self.line_31.setGeometry(QtCore.QRect(37, 30, 20, 211))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.pid_set_info_8 = QtWidgets.QLabel(self.frame_20)
        self.pid_set_info_8.setGeometry(QtCore.QRect(67, 50, 211, 181))
        self.pid_set_info_8.setObjectName("pid_set_info_8")
        self.line_32 = QtWidgets.QFrame(self.frame_20)
        self.line_32.setGeometry(QtCore.QRect(287, 30, 20, 211))
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.Reset_6 = QtWidgets.QPushButton(self.PID6)
        self.Reset_6.setGeometry(QtCore.QRect(450, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Reset_6.setFont(font)
        self.Reset_6.setObjectName("Reset_6")
        self.Apply_6 = QtWidgets.QPushButton(self.PID6)
        self.Apply_6.setGeometry(QtCore.QRect(350, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Apply_6.setFont(font)
        self.Apply_6.setObjectName("Apply_6")
        self.pid_set_widget.addTab(self.PID6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuinfo = QtWidgets.QMenu(self.menubar)
        self.menuinfo.setObjectName("menuinfo")
        self.menutrajectory = QtWidgets.QMenu(self.menubar)
        self.menutrajectory.setObjectName("menutrajectory")
        self.menuVisuakisation = QtWidgets.QMenu(self.menubar)
        self.menuVisuakisation.setObjectName("menuVisuakisation")
        MainWindow.setMenuBar(self.menubar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionopen_history = QtWidgets.QAction(MainWindow)
        self.actionopen_history.setObjectName("actionopen_history")
        self.Camera = QtWidgets.QAction(MainWindow)
        self.Camera.setObjectName("Camera")
        self.actionfiltered_camera = QtWidgets.QAction(MainWindow)
        self.actionfiltered_camera.setObjectName("actionfiltered_camera")
        self.actionPath_planer = QtWidgets.QAction(MainWindow)
        self.actionPath_planer.setObjectName("actionPath_planer")
        self.actionview_logs = QtWidgets.QAction(MainWindow)
        self.actionview_logs.setObjectName("actionview_logs")
        self.Camera_2 = QtWidgets.QAction(MainWindow)
        self.Camera_2.setObjectName("Camera_2")
        self.menufile.addAction(self.actionview_logs)
        self.menuinfo.addAction(self.actionhelp)
        self.menutrajectory.addAction(self.actionPath_planer)
        self.menuVisuakisation.addAction(self.Camera_2)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuinfo.menuAction())
        self.menubar.addAction(self.menutrajectory.menuAction())
        self.menubar.addAction(self.menuVisuakisation.menuAction())
        self.label.setBuddy(self.SpinBox_kp_1)
        self.label_5.setBuddy(self.SpinBox_kd_1)
        self.label_2.setBuddy(self.SpinBox_ki_1)
        self.label_3.setBuddy(self.SpinBox_kd_1)
        self.label_10.setBuddy(self.SpinBox_kd_1)
        self.label_11.setBuddy(self.SpinBox_ki_1)
        self.label_34.setBuddy(self.SpinBox_kp_1)
        self.label_41.setBuddy(self.SpinBox_kp_1)
        self.label_40.setBuddy(self.SpinBox_ki_1)
        self.label_39.setBuddy(self.SpinBox_kd_1)
        self.label_27.setBuddy(self.SpinBox_kp_1)
        self.label_25.setBuddy(self.SpinBox_kd_1)
        self.label_26.setBuddy(self.SpinBox_ki_1)
        self.label_42.setBuddy(self.SpinBox_kp_1)
        self.label_43.setBuddy(self.SpinBox_kd_1)
        self.label_44.setBuddy(self.SpinBox_ki_1)
        self.label_47.setBuddy(self.SpinBox_kp_1)
        self.label_48.setBuddy(self.SpinBox_kd_1)
        self.label_49.setBuddy(self.SpinBox_ki_1)

        self.retranslateUi(MainWindow)
        self.pid_set_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main Controller"))
        self.start_sim.setText(_translate("MainWindow", "Start Simulation"))
        self.stop_sim.setText(_translate("MainWindow", "Stop Simulation"))
        self.pause_sim.setText(_translate("MainWindow", "Pause"))
        self.title.setText(_translate("MainWindow", "Sim Params"))
        self.history.setText(_translate("MainWindow", "Save history"))
        self.pots.setText(_translate("MainWindow", "Ssave plots"))
        self.label_4.setText(_translate("MainWindow", "connected modules"))
        self.Apply_sim_param.setText(_translate("MainWindow", "Apply"))
        self.Reset_sim_params.setText(_translate("MainWindow", "Reset"))
        self.sim_info.setTitle(_translate("MainWindow", "sim info"))
        self.text.setText(_translate("MainWindow", "Sim time"))
        self.x_t.setText(_translate("MainWindow", "X(t) ="))
        self.w_g.setText(_translate("MainWindow", "w(g) ="))
        self.w_b.setText(_translate("MainWindow", "w(b) ="))
        self.alpha.setText(_translate("MainWindow", "alpha ="))
        self.gama.setText(_translate("MainWindow", "gama ="))
        self.beta.setText(_translate("MainWindow", "beta ="))
        self.z_t.setText(_translate("MainWindow", "Z(t) ="))
        self.v_t.setText(_translate("MainWindow", "V(t) ="))
        self.y_t.setText(_translate("MainWindow", "Y(t) ="))
        self.w_a.setText(_translate("MainWindow", "w(a) ="))
        self.label_50.setText(_translate("MainWindow", "0"))
        self.label_51.setText(_translate("MainWindow", "0"))
        self.label_52.setText(_translate("MainWindow", "0"))
        self.label_53.setText(_translate("MainWindow", "0"))
        self.label_54.setText(_translate("MainWindow", "0"))
        self.label_55.setText(_translate("MainWindow", "0"))
        self.label_56.setText(_translate("MainWindow", "0"))
        self.label_57.setText(_translate("MainWindow", "0"))
        self.label_58.setText(_translate("MainWindow", "0"))
        self.label_59.setText(_translate("MainWindow", "0"))
        self.Reset_sim.setText(_translate("MainWindow", "Reset"))
        self.connectioninfo.setTitle(_translate("MainWindow", "Connection"))
        self.connection_text.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Kp"))
        self.label_5.setText(_translate("MainWindow", "Kv"))
        self.label_2.setText(_translate("MainWindow", "Ki"))
        self.label_3.setText(_translate("MainWindow", "Kd"))
        self.pid_set_info.setText(_translate("MainWindow", "H"))
        self.Apply_1.setText(_translate("MainWindow", "Apply"))
        self.Reset_1.setText(_translate("MainWindow", "Reset"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.PID1), _translate("MainWindow", "PID 1"))
        self.pid_set_info_2.setText(_translate("MainWindow", "X"))
        self.label_10.setText(_translate("MainWindow", "Kd"))
        self.label_11.setText(_translate("MainWindow", "Ki"))
        self.label_34.setText(_translate("MainWindow", "Kp"))
        self.Reset_2.setText(_translate("MainWindow", "Reset"))
        self.Apply_2.setText(_translate("MainWindow", "Apply"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.PID2), _translate("MainWindow", "PID 2"))
        self.pid_set_info_5.setText(_translate("MainWindow", "Y"))
        self.label_41.setText(_translate("MainWindow", "Kp"))
        self.label_40.setText(_translate("MainWindow", "Ki"))
        self.label_39.setText(_translate("MainWindow", "Kd"))
        self.Reset_3.setText(_translate("MainWindow", "Reset"))
        self.Apply_3.setText(_translate("MainWindow", "Apply"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.PID3), _translate("MainWindow", "PID 3"))
        self.label_27.setText(_translate("MainWindow", "Kp"))
        self.label_25.setText(_translate("MainWindow", "Kd"))
        self.label_26.setText(_translate("MainWindow", "Ki"))
        self.pid_set_info_6.setText(_translate("MainWindow", "Rotation"))
        self.Reset_4.setText(_translate("MainWindow", "Reset"))
        self.Apply_4.setText(_translate("MainWindow", "Apply"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.PID4), _translate("MainWindow", "PID 4"))
        self.label_42.setText(_translate("MainWindow", "Kp"))
        self.label_43.setText(_translate("MainWindow", "Kd"))
        self.label_44.setText(_translate("MainWindow", "Ki"))
        self.pid_set_info_7.setText(_translate("MainWindow", "alpha"))
        self.Reset_5.setText(_translate("MainWindow", "Reset"))
        self.Apply_5.setText(_translate("MainWindow", "Apply"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.PID5), _translate("MainWindow", "PID 5"))
        self.label_47.setText(_translate("MainWindow", "Kp"))
        self.label_48.setText(_translate("MainWindow", "Kd"))
        self.label_49.setText(_translate("MainWindow", "Ki"))
        self.pid_set_info_8.setText(_translate("MainWindow", "beta"))
        self.Reset_6.setText(_translate("MainWindow", "Reset"))
        self.Apply_6.setText(_translate("MainWindow", "Apply"))
        self.pid_set_widget.setTabText(self.pid_set_widget.indexOf(self.PID6), _translate("MainWindow", "PID 6"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuinfo.setTitle(_translate("MainWindow", "Info"))
        self.menutrajectory.setTitle(_translate("MainWindow", "Trajectory"))
        self.menuVisuakisation.setTitle(_translate("MainWindow", "Visualization"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionopen_history.setText(_translate("MainWindow", "open history"))
        self.Camera.setText(_translate("MainWindow", "Camera"))
        self.actionfiltered_camera.setText(_translate("MainWindow", "filtered camera"))
        self.actionPath_planer.setText(_translate("MainWindow", "Path planer"))
        self.actionview_logs.setText(_translate("MainWindow", "view logs"))
        self.Camera_2.setText(_translate("MainWindow", "Camera"))
